package io.github.alirostom1.logismart.model.enums;

public enum EPermission {
    COURIER_SAVE,
    COURIER_GET,
    COURIER_READ,
    COURIER_DELETE,
    COURIER_READ_OWN,

    DELIVERY_SAVE,
    DELIVERY_READ,
    DELIVERY_DELETE,
    DELIVERY_ASSIGN,
    DELIVERY_READ_OWN,
    DELIVERY_UPDATE_STATUS,

    PRODUCT_SAVE,
    PRODUCT_READ,
    PRODUCT_DELETE,
    PRODUCT_ASSIGN,
    PRODUCT_READ_OWN,

    SENDER_READ,
    SENDER_SAVE,
    SENDER_SAVE_OWN,
    SENDER_DELETE,
    SENDER_READ_OWN,

    PERMISSION_SAVE,
    PERMISSION_DELETE,
    PERMISSION_ASSIGN,
    PERMISSION_REVOKE,
    PERMISSION_READ,

}
